dbtlearn:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: *****
      user: "****"
      password: "******"
      database: "*****"
      warehouse: "*****"
      schema: "****"
      role: "******"

