dbtlearn:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ysijldo-cl63614
      user: "dbt"
      password: "dbtPassword123"
      database: "AIRBNB"
      warehouse: "COMPUTE_WH"
      schema: "RAW"
      role: "transform"

